import assert from 'node:assert/strict';
import test from 'node:test';
import { canViewStaffPage } from '../src/lib/staffNavigation';
test('navigation separates staff operations, account administration, and chain finance', () => {
  assert.equal(canViewStaffPage(null, '/admin/branches'), false);
  assert.equal(canViewStaffPage(null, '/admin/users'), false);
  assert.equal(canViewStaffPage('SYSTEM_ADMINISTRATOR', '/admin/branches'), true);
  assert.equal(canViewStaffPage('SYSTEM_ADMINISTRATOR', '/admin/users'), true);
  assert.equal(canViewStaffPage('AUDITOR', '/admin/branches'), false);
  assert.equal(canViewStaffPage('AUDITOR', '/admin/users'), true);
  assert.equal(canViewStaffPage('SYSTEM_ADMINISTRATOR', '/bookings/new'), false);
  assert.equal(canViewStaffPage('SYSTEM_ADMINISTRATOR', '/admin/reports'), false);
  assert.equal(canViewStaffPage('FRONT_DESK', '/bookings/new'), true);
  assert.equal(canViewStaffPage('FRONT_DESK', '/admin/branches'), false);
  assert.equal(canViewStaffPage('FRONT_DESK', '/admin/users'), false);
  assert.equal(canViewStaffPage('CHAIN_MANAGER', '/admin/reports'), true);
  assert.equal(canViewStaffPage('AUDITOR', '/admin/audit'), true);
  assert.equal(canViewStaffPage('SERVICE_STAFF', '/admin/config'), false);
  assert.equal(canViewStaffPage(null, '/billing/invoice'), false);
  assert.equal(canViewStaffPage('FRONT_DESK', '/billing/invoice'), true);
  assert.equal(canViewStaffPage('SERVICE_STAFF', '/billing/invoice'), true);
  assert.equal(canViewStaffPage('BRANCH_MANAGER', '/billing/invoice'), true);
  assert.equal(canViewStaffPage('CHAIN_MANAGER', '/billing/invoice'), true);
  assert.equal(canViewStaffPage('AUDITOR', '/billing/invoice'), true);
  assert.equal(canViewStaffPage('SYSTEM_ADMINISTRATOR', '/billing/invoice'), false);
});
